theme: jekyll-theme-modernist
title: Nathaniel Ortiz
description: 3rd year Electrical Engineering major at the University of California, Riverside
show_downloads: false
google_analytics: UA-163412901-1
github:
  is_project_page: false
owner:
  name: Nathaniel Ortiz
  avatar: profile.jpg
  bio: "This is a sample Jekyll academic website."
  email: nortiz@engr.ucr.edu
  linkedin: nathaniel-ortiz
