theme: jekyll-theme-minimal
title: Nathaniel Ortiz
show_downloads: false
google_analytics: UA-163412901-1
github:
  repository_url: https://github.com/thelectronicnub
logo: IMG_20200312_010616_003.jpg
title: Nathaniel Ortiz
description: Undergraduate Electrical Engineering Student at the University of California, Riverside
