theme: jekyll-theme-modernist
title: Nathaniel Ortiz
description: 3rd year Electrical Engineering major at the University of California, Riverside
show_downloads: false
google_analytics: UA-163412901-1
